spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:13306/flowable?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: root